import { type AssHeader, type Cue, defaultAssFields, newCueId, type SubtitleDoc } from '../document';

/** Event fields of ASS files, in the order Aegisub writes them. */
const ASS_EVENT_FORMAT = ['Layer', 'Start', 'End', 'Style', 'Name', 'MarginL', 'MarginR', 'MarginV', 'Effect', 'Text'];

/** `0:01:02.34`: hours, minutes, seconds, hundredths. */
function parseTime(value: string): number | null {
	const match = /^\s*(\d+):(\d{1,2}):(\d{1,2})(?:[.,](\d+))?\s*$/.exec(value);
	if (!match) return null;
	const [, h = '0', m = '0', s = '0', fraction = '0'] = match;
	return (Number(h) * 3600 + Number(m) * 60 + Number(s)) * 1000 + Math.round(Number(`0.${fraction}`) * 1000);
}

/** `0:01:02.34`. ASS counts hundredths of a second. */
export function assTime(milliseconds: number): string {
	const cs = Math.max(0, Math.round(milliseconds / 10));
	const h = Math.floor(cs / 360_000);
	const m = Math.floor(cs / 6000) % 60;
	const s = Math.floor(cs / 100) % 60;
	return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs % 100).padStart(2, '0')}`;
}

function scriptValue(head: string, key: string): string | null {
	const match = new RegExp(`^${key}\\s*:\\s*(.*)$`, 'im').exec(head);
	return match?.[1]?.trim() || null;
}

function headerInfo(head: string): Omit<AssHeader, 'head' | 'format' | 'tail'> {
	const width = Number(scriptValue(head, 'PlayResX'));
	const height = Number(scriptValue(head, 'PlayResY'));
	const styles = [...head.matchAll(/^Style\s*:\s*([^,\n]*)/gim)].map((match) => (match[1] ?? '').trim());
	return {
		playRes: width > 0 && height > 0 ? { width, height } : null,
		title: scriptValue(head, 'Title'),
		styles,
		scriptType: scriptValue(head, 'ScriptType'),
	};
}

/**
 * Reads ASS or SSA. Everything around the events (script info, styles, embedded fonts) is kept as
 * written, so saving an ASS file again changes only the lines that were edited.
 */
export function parseAss(text: string): SubtitleDoc | null {
	const lines = text.replace(/\r\n?/g, '\n').split('\n');
	const eventsAt = lines.findIndex((line) => /^\s*\[events\]\s*$/i.test(line));
	if (!/^\s*\[script info\]/im.test(text) && eventsAt === -1) return null;
	const headLines = eventsAt === -1 ? lines : lines.slice(0, eventsAt);
	let tailAt = lines.length;
	let format = ASS_EVENT_FORMAT;
	const cues: Cue[] = [];
	if (eventsAt !== -1) {
		for (let i = eventsAt + 1; i < lines.length; i++) {
			const line = lines[i] ?? '';
			if (/^\s*\[.*\]\s*$/.test(line)) {
				tailAt = i;
				break;
			}
			const match = /^\s*(Format|Dialogue|Comment)\s*:\s?(.*)$/i.exec(line);
			if (!match) continue;
			const [, kind = '', rest = ''] = match;
			if (kind.toLowerCase() === 'format') {
				format = rest.split(',').map((name) => name.trim());
				continue;
			}
			const values = splitFields(rest, format.length);
			const fields: Record<string, string> = {};
			let start: number | null = null;
			let end: number | null = null;
			let body = '';
			format.forEach((name, index) => {
				const key = name.toLowerCase();
				const value = values[index] ?? '';
				if (key === 'start') start = parseTime(value);
				else if (key === 'end') end = parseTime(value);
				else if (key === 'text') body = value;
				else fields[key] = value;
			});
			if (start === null || end === null) continue;
			const cue: Cue = { id: newCueId(), start, end: Math.max(start, end), text: body, fields };
			if (kind.toLowerCase() === 'comment') cue.comment = true;
			cues.push(cue);
		}
	}
	const head = headLines.join('\n').trimEnd();
	return {
		format: 'ass',
		cues,
		ass: { head, format, tail: lines.slice(tailAt).join('\n').trim(), ...headerInfo(head) },
		vttHeader: null,
	};
}

/** Splits an event line into `count` fields: the last one, the text, may hold commas. */
function splitFields(rest: string, count: number): string[] {
	const values: string[] = [];
	let from = 0;
	for (let k = 0; k < count - 1; k++) {
		const comma = rest.indexOf(',', from);
		if (comma === -1) break;
		values.push(rest.slice(from, comma).trim());
		from = comma + 1;
	}
	values.push(rest.slice(from));
	return values;
}

/**
 * The header given to subtitles converted to ASS: one style close to what players show for SRT
 * (white, black outline, bottom centre), sized for the resolution positions refer to.
 */
export function defaultAssHeader(title: string, playRes = { width: 1920, height: 1080 }): AssHeader {
	const scale = playRes.height / 1080;
	const size = Math.round(66 * scale);
	const outline = Math.round(3.4 * scale * 10) / 10;
	const shadow = Math.round(1.4 * scale * 10) / 10;
	const marginH = Math.round(96 * scale);
	const marginV = Math.round(54 * scale);
	const head = [
		'[Script Info]',
		'; Script generated by Vixely',
		`Title: ${title}`,
		'ScriptType: v4.00+',
		'WrapStyle: 0',
		'ScaledBorderAndShadow: yes',
		'YCbCr Matrix: None',
		`PlayResX: ${playRes.width}`,
		`PlayResY: ${playRes.height}`,
		'',
		'[V4+ Styles]',
		'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
		`Style: Default,Arial,${size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,${outline},${shadow},2,${marginH},${marginH},${marginV},1`,
	].join('\n');
	return { head, format: ASS_EVENT_FORMAT, tail: '', playRes, title, styles: ['Default'], scriptType: 'v4.00+' };
}

/** Writes ASS from cues already in ASS markup, in the order given (it sets which line draws on top). */
export function writeAss(cues: readonly Cue[], header: AssHeader): string {
	const defaults = defaultAssFields();
	const events = cues.map((cue) => {
		const values = header.format.map((name) => {
			const key = name.toLowerCase();
			if (key === 'start') return assTime(cue.start);
			if (key === 'end') return assTime(cue.end);
			// A line break would end the event: the text keeps them as \N.
			if (key === 'text') return cue.text.replace(/\r?\n/g, '\\N');
			return cue.fields?.[key] ?? defaults[key] ?? '';
		});
		return `${cue.comment ? 'Comment' : 'Dialogue'}: ${values.join(',')}`;
	});
	const parts = [header.head, '', '[Events]', `Format: ${header.format.join(', ')}`, ...events];
	if (header.tail) parts.push('', header.tail);
	return `${parts.join('\r\n').replace(/\r?\n/g, '\r\n')}\r\n`;
}
