import { VERSION } from '@/lib/version';
import { type AssHeader, type Cue, defaultAssFields, newCueId, type SubtitleDoc } from '../document';

/** Event fields of ASS files, in the order Aegisub writes them. */
const ASS_EVENT_FORMAT = ['Layer', 'Start', 'End', 'Style', 'Name', 'MarginL', 'MarginR', 'MarginV', 'Effect', 'Text'];

/** `0:01:02.34`: hours, minutes, seconds, hundredths. */
function parseTime(value: string): number | null {
	const match = /^\s*(\d+):(\d{1,2}):(\d{1,2})(?:[.,](\d+))?\s*$/.exec(value);
	if (!match) return null;
	const [, h = '0', m = '0', s = '0', fraction = '0'] = match;
	return (Number(h) * 3600 + Number(m) * 60 + Number(s)) * 1000 + Math.round(Number(`0.${fraction}`) * 1000);
}

/** `0:01:02.34`. ASS counts hundredths of a second. */
export function assTime(milliseconds: number): string {
	const cs = Math.max(0, Math.round(milliseconds / 10));
	const h = Math.floor(cs / 360_000);
	const m = Math.floor(cs / 6000) % 60;
	const s = Math.floor(cs / 100) % 60;
	return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs % 100).padStart(2, '0')}`;
}

function scriptValue(head: string, key: string): string | null {
	const match = new RegExp(`^${key}\\s*:\\s*(.*)$`, 'im').exec(head);
	return match?.[1]?.trim() || null;
}

function headerInfo(head: string): Omit<AssHeader, 'head' | 'format' | 'tail'> {
	const width = Number(scriptValue(head, 'PlayResX'));
	const height = Number(scriptValue(head, 'PlayResY'));
	const styles = [...head.matchAll(/^Style\s*:\s*([^,\n]*)/gim)].map((match) => (match[1] ?? '').trim());
	return {
		playRes: width > 0 && height > 0 ? { width, height } : null,
		title: scriptValue(head, 'Title'),
		styles,
		scriptType: scriptValue(head, 'ScriptType'),
	};
}

/**
 * Reads ASS or SSA. Everything around the events (script info, styles, embedded fonts) is kept as
 * written, so saving an ASS file again changes only the lines that were edited.
 */
export function parseAss(text: string): SubtitleDoc | null {
	const lines = text.replace(/\r\n?/g, '\n').split('\n');
	const eventsAt = lines.findIndex((line) => /^\s*\[events\]\s*$/i.test(line));
	if (!/^\s*\[script info\]/im.test(text) && eventsAt === -1) return null;
	const headLines = eventsAt === -1 ? lines : lines.slice(0, eventsAt);
	let tailAt = lines.length;
	let format = ASS_EVENT_FORMAT;
	const cues: Cue[] = [];
	if (eventsAt !== -1) {
		for (let i = eventsAt + 1; i < lines.length; i++) {
			const line = lines[i] ?? '';
			if (/^\s*\[.*\]\s*$/.test(line)) {
				tailAt = i;
				break;
			}
			const match = /^\s*(Format|Dialogue|Comment)\s*:\s?(.*)$/i.exec(line);
			if (!match) continue;
			const [, kind = '', rest = ''] = match;
			if (kind.toLowerCase() === 'format') {
				format = rest.split(',').map((name) => name.trim());
				continue;
			}
			const values = splitFields(rest, format.length);
			const fields: Record<string, string> = {};
			let start: number | null = null;
			let end: number | null = null;
			let body = '';
			format.forEach((name, index) => {
				const key = name.toLowerCase();
				const value = values[index] ?? '';
				if (key === 'start') start = parseTime(value);
				else if (key === 'end') end = parseTime(value);
				else if (key === 'text') body = value;
				else fields[key] = value;
			});
			if (start === null || end === null) continue;
			const cue: Cue = { id: newCueId(), start, end: Math.max(start, end), text: body, fields };
			if (kind.toLowerCase() === 'comment') cue.comment = true;
			cues.push(cue);
		}
	}
	const head = headLines.join('\n').trimEnd();
	return {
		format: 'ass',
		cues,
		ass: { head, format, tail: lines.slice(tailAt).join('\n').trim(), ...headerInfo(head) },
		vttHeader: null,
	};
}

/** Splits an event line into `count` fields: the last one, the text, may hold commas. */
function splitFields(rest: string, count: number): string[] {
	const values: string[] = [];
	let from = 0;
	for (let k = 0; k < count - 1; k++) {
		const comma = rest.indexOf(',', from);
		if (comma === -1) break;
		values.push(rest.slice(from, comma).trim());
		from = comma + 1;
	}
	values.push(rest.slice(from));
	return values;
}

/**
 * The header given to subtitles converted to ASS: one style close to what players show for SRT
 * (white, black outline, bottom centre), sized for the resolution positions refer to.
 */
export function defaultAssHeader(title: string, playRes = { width: 1920, height: 1080 }): AssHeader {
	const style = playRes.height > playRes.width * 1.1 ? verticalStyle(playRes) : wideStyle(playRes);
	const head = [
		'[Script Info]',
		'; Script generated by Vixely',
		`Title: ${title}`,
		'ScriptType: v4.00+',
		'WrapStyle: 0',
		'ScaledBorderAndShadow: yes',
		'YCbCr Matrix: None',
		`PlayResX: ${playRes.width}`,
		`PlayResY: ${playRes.height}`,
		'',
		'[V4+ Styles]',
		'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
		`Style: Default,Arial,${style.size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,${style.bold ? -1 : 0},0,0,0,100,100,0,0,1,${style.outline},${style.shadow},2,${style.marginH},${style.marginH},${style.marginV},1`,
	].join('\n');
	return { head, format: ASS_EVENT_FORMAT, tail: '', playRes, title, styles: ['Default'], scriptType: 'v4.00+' };
}

interface DefaultStyle {
	size: number;
	bold: boolean;
	outline: number;
	shadow: number;
	marginH: number;
	marginV: number;
}

/** Films and series: the usual white text with a thin outline, low in the picture. */
function wideStyle(playRes: { width: number; height: number }): DefaultStyle {
	const scale = playRes.height / 1080;
	return {
		size: Math.round(66 * scale),
		bold: false,
		outline: Math.round(3.4 * scale * 10) / 10,
		shadow: Math.round(1.4 * scale * 10) / 10,
		marginH: Math.round(96 * scale),
		marginV: Math.round(54 * scale),
	};
}

/**
 * TikTok, Reels and Shorts: bold captions with a heavy outline, a tenth of the width in from each
 * side, and raised to about 30 % of the height, clear of the caption, buttons and progress bar the
 * apps draw over the bottom of the video.
 */
function verticalStyle(playRes: { width: number; height: number }): DefaultStyle {
	const scale = playRes.width / 1080;
	return {
		size: Math.round(80 * scale),
		bold: true,
		outline: Math.round(5 * scale * 10) / 10,
		shadow: 0,
		marginH: Math.round(playRes.width * 0.1),
		marginV: Math.round(playRes.height * 0.3),
	};
}

/** Writes ASS from cues already in ASS markup, in the order given (it sets which line draws on top). */
export function writeAss(cues: readonly Cue[], header: AssHeader): string {
	const defaults = defaultAssFields();
	const events = cues.map((cue) => {
		const values = header.format.map((name) => {
			const key = name.toLowerCase();
			if (key === 'start') return assTime(cue.start);
			if (key === 'end') return assTime(cue.end);
			// A line break would end the event: the text keeps them as \N.
			if (key === 'text') return cue.text.replace(/\r?\n/g, '\\N');
			return cue.fields?.[key] ?? defaults[key] ?? '';
		});
		return `${cue.comment ? 'Comment' : 'Dialogue'}: ${values.join(',')}`;
	});
	const head = stampGenerator(header.head, header.generator ?? defaultGenerator());
	const parts = [head, '', '[Events]', `Format: ${header.format.join(', ')}`, ...events];
	if (header.tail) parts.push('', header.tail);
	return `${parts.join('\r\n').replace(/\r?\n/g, '\r\n')}\r\n`;
}

/** The maker scripts name unless told otherwise: this app, at this version. */
export function defaultGenerator(): string {
	return `Vixely ${VERSION}`;
}

/** A line of `[Script Info]`: `Key: value`. */
export interface ScriptEntry {
	key: string;
	value: string;
}

/** Where `[Script Info]` starts and ends in the head, by line. */
function scriptInfoBounds(lines: readonly string[]): { from: number; to: number } | null {
	const from = lines.findIndex((line) => /^\s*\[script info\]\s*$/i.test(line));
	if (from === -1) return null;
	let to = lines.length;
	for (let i = from + 1; i < lines.length; i++) {
		if (/^\s*\[.*\]\s*$/.test(lines[i] ?? '')) {
			to = i;
			break;
		}
	}
	return { from, to };
}

/** The fields of `[Script Info]`, in order; comments (`;`) left out. */
export function readScriptInfo(head: string): ScriptEntry[] {
	const lines = head.split('\n');
	const bounds = scriptInfoBounds(lines);
	if (!bounds) return [];
	const entries: ScriptEntry[] = [];
	for (const line of lines.slice(bounds.from + 1, bounds.to)) {
		const match = /^\s*([^;!:][^:]*?)\s*:\s?(.*)$/.exec(line);
		if (match) entries.push({ key: match[1] ?? '', value: (match[2] ?? '').trim() });
	}
	return entries;
}

/** The program named as the script's maker: `; Script generated by …`. */
export function readGenerator(head: string): string | null {
	return /^\s*;\s*Script generated by\s+(.*)$/im.exec(head)?.[1]?.trim() ?? null;
}

/**
 * The head with `[Script Info]` holding `entries`, in their order, and `generator` named as its
 * maker. Comments other than the maker's stay; the rest of the head is left as it was.
 */
export function writeScriptInfo(head: string, entries: readonly ScriptEntry[], generator: string): string {
	const lines = head.split('\n');
	const bounds = scriptInfoBounds(lines) ?? { from: -1, to: -1 };
	const before = bounds.from === -1 ? [] : lines.slice(0, bounds.from);
	const after = bounds.from === -1 ? lines : lines.slice(bounds.to);
	const kept = bounds.from === -1 ? [] : lines.slice(bounds.from + 1, bounds.to);
	// The maker's comment and the web address Aegisub adds under it make way for the new maker.
	const comments = kept.filter(
		(line) =>
			/^\s*[;!]/.test(line) &&
			!/^\s*;\s*Script generated by/i.test(line) &&
			!/^\s*;\s*https?:\/\/(www\.)?aegisub/i.test(line),
	);
	const section = [
		'[Script Info]',
		...(generator.trim() ? [`; Script generated by ${generator.trim()}`] : []),
		...comments,
		...entries.filter((entry) => entry.key.trim()).map((entry) => `${entry.key.trim()}: ${entry.value.trim()}`),
	];
	const rest = after.join('\n').replace(/^\n+/, '');
	return [...before, ...section, ...(rest ? ['', rest] : [])].join('\n').trimEnd();
}

/** The header with `[Script Info]` rewritten, and what it tells (resolution, title) read again. */
export function withScriptInfo(header: AssHeader, entries: readonly ScriptEntry[], generator: string): AssHeader {
	const head = writeScriptInfo(header.head, entries, generator);
	return { ...header, head, generator, ...headerInfo(head) };
}

/** The head as the editor gives it: made by Vixely, this version, its other fields untouched. */
export function stampGenerator(head: string, generator: string): string {
	return writeScriptInfo(head, readScriptInfo(head), generator);
}
