/**
 * Access point to vixely-audio, the audio analysis module compiled to WebAssembly. Loaded by the
 * audio editor only. `src/wasm/vixely-audio/` is generated by `bun run build:wasm`.
 */
import type * as Audio from './vixely-audio/vixely_audio.js';

let loading: Promise<typeof Audio> | null = null;

export async function loadAudio(): Promise<typeof Audio> {
	loading ??= import('./vixely-audio/vixely_audio.js').then(async (audio) => {
		await audio.default();
		return audio;
	});
	return loading;
}
