/**
 * Access point to vixely-core, the Rust module compiled to WebAssembly.
 *
 * The module is loaded on first use and shared afterwards. `src/wasm/vixely-core/` is generated by
 * `bun run build:wasm` and is not committed.
 */
import type * as Core from './vixely-core/vixely_core.js';

let loading: Promise<typeof Core> | null = null;

export async function loadCore(): Promise<typeof Core> {
	loading ??= import('./vixely-core/vixely_core.js').then(async (core) => {
		await core.default();
		return core;
	});
	return loading;
}
