/**
 * Access point to vixely-subs, the subtitle track module compiled to WebAssembly: PGS pictures
 * decoded for the preview and written back. Files are read in `src/workers/subs.worker.ts`.
 * `src/wasm/vixely-subs/` is generated by `bun run build:wasm`.
 */
import type * as Subs from './vixely-subs/vixely_subs.js';

let loading: Promise<typeof Subs> | null = null;

export async function loadSubs(): Promise<typeof Subs> {
	loading ??= import('./vixely-subs/vixely_subs.js').then(async (subs) => {
		await subs.default();
		return subs;
	});
	return loading;
}
