/**
 * Access point to vixely-truehd, the Dolby TrueHD decoder compiled to WebAssembly. Loaded when a
 * film has TrueHD sound. `src/wasm/vixely-truehd/` is generated by `bun run build:wasm`.
 */
import type * as TrueHd from './vixely-truehd/vixely_truehd.js';

let loading: Promise<typeof TrueHd> | null = null;

export async function loadTrueHd(): Promise<typeof TrueHd> {
	loading ??= import('./vixely-truehd/vixely_truehd.js').then(async (truehd) => {
		await truehd.default();
		return truehd;
	});
	return loading;
}
