/**
 * Writes src/styles/tokens.css from the token derivation in src/ui/theme.
 *
 * The stylesheet is generated rather than hand-written because every accent is
 * contrast-corrected (Catppuccin is not AA-conformant as shipped). A unit test
 * fails the CI when the committed file drifts from the derivation.
 */
import { buildThemeTokens } from "../src/ui/theme/tokens.ts";

const HEADER = `/* Generated by scripts/generate-tokens.ts — do not edit by hand. */`;

function block(selector: string, tokens: Readonly<Record<string, string>>, indent = "\t"): string {
	const body = Object.entries(tokens)
		.map(([name, value]) => `${indent}${name}: ${value};`)
		.join("\n");
	return `${selector} {\n${body}\n}`;
}

/** `data-editor` on the root is what recolours the whole accent family. */
function accentAliases(editor: string): string {
	return [
		`\t--accent: var(--accent-${editor});`,
		`\t--accent-solid: var(--accent-${editor}-solid);`,
		`\t--accent-on: var(--accent-${editor}-on);`,
		`\t--accent-surface: var(--accent-${editor}-surface);`,
		`\t--focus-ring: var(--accent-${editor});`,
	].join("\n");
}

export function renderTokensCss(): string {
	const light = buildThemeTokens("light");
	const dark = buildThemeTokens("dark");

	const editors = ["image", "video", "gif", "audio", "subtitles"];

	return [
		HEADER,
		"",
		block(':root, [data-theme="light"]', light),
		"",
		block('[data-theme="dark"]', dark),
		"",
		"@media (prefers-color-scheme: dark) {",
		block('\t:root:not([data-theme="light"])', dark, "\t\t"),
		"}",
		"",
		...editors.map((editor) => `[data-editor="${editor}"] {\n${accentAliases(editor)}\n}`),
		"",
	].join("\n");
}

if (import.meta.main) {
	const target = new URL("../src/styles/tokens.css", import.meta.url);
	await Bun.write(target, renderTokensCss());
	console.log(`wrote ${target.pathname}`);
}
