/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ToolsAudioRouteImport } from './routes/tools/audio'
import { Route as ToolsGifRouteImport } from './routes/tools/gif'
import { Route as ToolsImageRouteImport } from './routes/tools/image'
import { Route as ToolsSubtitlesRouteImport } from './routes/tools/subtitles'
import { Route as ToolsVideoRouteImport } from './routes/tools/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAudioRoute = ToolsAudioRouteImport.update({
  id: '/tools/audio',
  path: '/tools/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGifRoute = ToolsGifRouteImport.update({
  id: '/tools/gif',
  path: '/tools/gif',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageRoute = ToolsImageRouteImport.update({
  id: '/tools/image',
  path: '/tools/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSubtitlesRoute = ToolsSubtitlesRouteImport.update({
  id: '/tools/subtitles',
  path: '/tools/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoRoute = ToolsVideoRouteImport.update({
  id: '/tools/video',
  path: '/tools/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/tools/audio': typeof ToolsAudioRoute
  '/tools/gif': typeof ToolsGifRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/subtitles': typeof ToolsSubtitlesRoute
  '/tools/video': typeof ToolsVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/tools/audio': typeof ToolsAudioRoute
  '/tools/gif': typeof ToolsGifRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/subtitles': typeof ToolsSubtitlesRoute
  '/tools/video': typeof ToolsVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/tools/audio': typeof ToolsAudioRoute
  '/tools/gif': typeof ToolsGifRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/subtitles': typeof ToolsSubtitlesRoute
  '/tools/video': typeof ToolsVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/tools/audio'
    | '/tools/gif'
    | '/tools/image'
    | '/tools/subtitles'
    | '/tools/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/tools/audio'
    | '/tools/gif'
    | '/tools/image'
    | '/tools/subtitles'
    | '/tools/video'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/tools/audio'
    | '/tools/gif'
    | '/tools/image'
    | '/tools/subtitles'
    | '/tools/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ToolsAudioRoute: typeof ToolsAudioRoute
  ToolsGifRoute: typeof ToolsGifRoute
  ToolsImageRoute: typeof ToolsImageRoute
  ToolsSubtitlesRoute: typeof ToolsSubtitlesRoute
  ToolsVideoRoute: typeof ToolsVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/audio': {
      id: '/tools/audio'
      path: '/tools/audio'
      fullPath: '/tools/audio'
      preLoaderRoute: typeof ToolsAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/gif': {
      id: '/tools/gif'
      path: '/tools/gif'
      fullPath: '/tools/gif'
      preLoaderRoute: typeof ToolsGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image': {
      id: '/tools/image'
      path: '/tools/image'
      fullPath: '/tools/image'
      preLoaderRoute: typeof ToolsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/subtitles': {
      id: '/tools/subtitles'
      path: '/tools/subtitles'
      fullPath: '/tools/subtitles'
      preLoaderRoute: typeof ToolsSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video': {
      id: '/tools/video'
      path: '/tools/video'
      fullPath: '/tools/video'
      preLoaderRoute: typeof ToolsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ToolsAudioRoute: ToolsAudioRoute,
  ToolsGifRoute: ToolsGifRoute,
  ToolsImageRoute: ToolsImageRoute,
  ToolsSubtitlesRoute: ToolsSubtitlesRoute,
  ToolsVideoRoute: ToolsVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
